---
galaxy_info:
  author: Sriram Sitharaman
  description: emacs
  company: SOIC 
  license:
    - IUB
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 23
        - 24
    - name: Ubuntu
      versions:
        - xenial
    - name: Alpine
      versions:
        - all

  galaxy_tags:
    - development

dependencies: []