---

- name: create hbase zookeeper data directory
  file: path={{ hbase_zookeeper_data_dir }} state=directory owner={{ hadoop_user }} group={{ hadoop_group }}

# name: create hbase zookeeper systemd service file
#  template: src=systemd/hbase-zookeeper.service.j2 dest=/etc/systemd/system/hbase-zookeeper.service

# name: start hbase zookeeper
#  service: name=hbase-zookeeper state=started enabled=yes
